### PR TITLE
Merged #62 #65 #69 and added tests using gh-actions

### PR DESCRIPTION
**Pull request by GhostOps77**
I've did so many changes in this repo

- Added support in click's autocompletion
    -  fixes: #68
    - PR: #69
- Filter hidden commands & options
    - fixes: #64
    - PR: #65
- Pass top-level args to subcommand invocation
    - fixes: #58 
    - PR: #62
- Switched from travis CI to Github-Actions for testing, fixes:
    - #74
    - #80

I've merged all those PR's and gave some test cases, that run in pytest and tox
And that still give only 75% of coverage in pytest results, cuz some testing should be done by passing in command line arguments, which is impossible with this type of code structure

I tried my best to cover the test cases for each PR, but the code still needs some restructuring, which can maybe provide an opportunity to run command line argument tests in pytest

I've also made test cases for click v7.1.2 (cuz I saw that this module supports click v7)

Ignore the blank/auto name suggested commits, It's just me being lazy

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
it would be better and easier if this pr is split into smaller ones

**Comment by GhostOps77** [comment]
which means?
do i need to make separate branch for each changes?

**Comment by auvipy** [comment]
yes we can start with the new CI first

**Comment by auvipy** [comment]
you can pull from master

**Pull request closed without merging**
