### PR TITLE
Updated tests

### PR DESCRIPTION
**Pull request by GhostOps77**
Updated and Improved tests a little bit

This PR has some little bit tidy-ed up code for tests

### CODE REVIEW

**Comment by GhostOps77** [comment]
This PR also solved this issue
- #56

**Comment by GhostOps77** [comment]
As the previous PRs have solved this issue
- #56 

It's better to close this issue as well, and I've added a help param to an option in the `tests/test_basic.py` file to test it

And you can also close this issue as well, as the `CommandCollection` does get supported to the current version of click-repl
- #39

**Comment by GhostOps77** [comment]
Does this module support all the way up to python v2.7?

**Review by auvipy — APPROVED** [review]

**Comment by GhostOps77** [comment]
Does this module support all the way up to python v2.7?
cuz if not, you can close this issue as well 
- #71 

I didn't make any test cases for python 2.7, and i don't think i would add those test cases and py2.7 support for this module, as py2 is dead 3 years ago

**Pull request merged**
