### PR TITLE
fix AssertionError due to non-unicode prompt on python 2.7.x

### PR DESCRIPTION
**Pull request by cosminbasca**
- added .gitignore support for intellij based projects (generated with the intellij ignore plugin)
- a bit more PEP8 compliance (minor styling)
- using prompt instead of get_input (deprecated)
- fixed the message prompt to be a unicode (would crash on Python 2.7.x with an assertion error)

### CODE REVIEW

**Comment by untitaker** [comment]
>added .gitignore support for intellij based projects (generated with the intellij ignore plugin)

Some entries are now doubled

>a bit more PEP8 compliance (minor styling)

:+1:

>using prompt instead of get_input (deprecated)

:+1:

>fixed the message prompt to be a unicode (would crash on Python 2.7.x with an assertion error)

:+1:

----

Could you separate those in different pull requests? Thanks!

**Comment by cosminbasca** [comment]
I'm not sure how to split those into separate pull requests as they are all part of a single commit. The alternative is to close the pull requests, redo the changes one by one and create new pull requests for each. That feels like overkill for the simple changes in the pull request. If you know a better way please let me know, 

Cheers,
Cosmin

**Comment by untitaker** [comment]
Then please split them into separate commits at least.

This is possible by doing `git reset --hard HEAD^1`, and then committing your
changes separately. Then `git push --force`.

If that's not possible I will do it myself.

**Comment by untitaker** [comment]
(reposting because github cut off everything after the first sentence)

Then please split them into separate commits.

This is possible by doing `git reset --hard HEAD^1`, and then committing your
changes separately. Then `git push --force`.

If that's not possible I will do it myself.

**Comment by cosminbasca** [comment]
thanks for the howto, the original commit is not split

**Comment by untitaker** [comment]
Excellent, thank you!

**Comment by cosminbasca** [comment]
:+1:

**Pull request merged**
