### PR TITLE
Added repl context object

### PR DESCRIPTION
**Pull request by GhostOps77**
similar to click's context object, but its for keeping track on the promptsession object.

By this, the user can modify the prompt in runtime, can also change the prompt text, and view history.

### CODE REVIEW

**Comment by GhostOps77** [comment]
@auvipy can u review this pls?

**Comment by auvipy** [comment]
Yes

**Review by auvipy — CHANGES_REQUESTED** [review]
checking the code changes, it seems to be a big rewrite but without any additional test cases. it would be helpful to know more detail about the goal of the change

**Comment by GhostOps77** [comment]
its just for giving the user full control over the prompt session object for utmost customization of the prompt.
changing prompt, and checking commands history are just some of them.

its also used for keeping track of each of its appropriate repl session, which will be useful if a repl is invoked inside an another repl

**Comment by GhostOps77** [comment]
@auvipy any more queries?

**Comment by auvipy** [comment]
why it was closed?

**Comment by GhostOps77** [comment]
@auvipy i included a small, dead code
idk how to rebase
so i deleted the branch

**Pull request closed without merging**
