### PR TITLE
Added Python 2 support

### PR DESCRIPTION
**Pull request by GhostOps77**
Make sure to merge this PR before release, to make this module support python 2 as well

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
why should we support python 2? it is EOL long ago.. so RIP py 2

**Comment by auvipy** [comment]
can you please elaborate why we still need python 2 support?

**Comment by GhostOps77** [comment]
The guy from this issue
- #93 
needs python 2 support for his module
Removing the support for python 2 from our module will make their job uneasy

And they do requested me to add python 2 feature in his module, as you can see from this issue from their repo [pywebm/pywebmtools#1279](https://github.com/pywbem/pywbemtools/issues/1279), they are depended on this module's future release

So, That's why I've decided to introduce python 2 support for this module (again)

For more queries, you can ask the guy from this issue #93 regarding the python 2 support of this module

**Comment by GhostOps77** [comment]
@auvipy And i'm also having a big trouble of contacting you, to talk about the pypi release of this module

**Comment by GhostOps77** [comment]
Sry, closed it by mistake

**Comment by auvipy** [comment]
why closed?

**Comment by GhostOps77** [comment]
@auvipy After some talk with the guy who requested py2 support, I've decided to not to support py2 for this module anymore, and they are ok with that

**Pull request closed without merging**
