### PR TITLE
Unhandled exception during autocomplete fix

### PR DESCRIPTION
**Pull request by opirko**
Fixes the issue mentioned in https://github.com/click-contrib/click-repl/issues/108

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
seems some builds are failing! can you check?

**Comment by opirko** [comment]
Okay, I think it's fixed. It was failing with Click 7 due to the missing `()` in Click decorators.

**Comment by auvipy** [comment]
its failing again. can you recheck? we might consider dropping click 7 very soon but before that....

**Comment by opirko** [comment]
Now it was due to `flake` saying I got one space before inline comment instead of two (only in python 3.7 test for some reason). Oh well, here's hoping third time is the charm :D

**Review by auvipy — APPROVED** [review]

**Comment by jathanism** [comment]
Nice to see this fixed. Any plans on releasing it anytime soon? Thanks!

**Comment by Fugue997** [comment]
Hello! A PYPI release for this would be greatly appreciated :D

**Comment by auvipy** [comment]
OK, thanks I will release one soon

**Comment by Fugue997** [comment]
Thank you so much 🙏

**Comment by s4n-cz** [comment]
> OK, thanks I will release one soon

@auvipy A release with the fix would be highly appreciated. The UsageError does not provide great user experience.  I tried to bypass it and specify directly in my pyproject.toml dependencies:
```
  "click-repl @ git+https://github.com/click-contrib/click-repl.git@f08ba3919028a553b5e4e3218958d761fad16b5d",
```

which works locally, but fails when releasing to PyPI (this feature is not supported there) :disappointed:

**Comment by auvipy** [comment]
Sorry, i got so many packages to maintain and now got a baby to look after now. I have plans to release a new version before the end of march.

**Comment by alor** [comment]
any chance to see this released in a 0.3.1 package?  thanks

**Pull request merged**
